version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres-user
      - POSTGRES_PORT=5432
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_db

  order-service:
    build: ./order-service
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres-order
      - POSTGRES_PORT=5432
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order_db # Make sure to set this to your order DB

  inventory-service:
    build: ./inventory-service
    ports:
      - "3002:3002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres-inventory
      - POSTGRES_PORT=5432
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_password
      - POSTGRES_DB=inventory_db

  shipping-service:
    build: ./shipping-service
    ports:
      - "3003:3003"
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ message broker
      - "15673:15672" # RabbitMQ management console
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres-user:
    image: postgres:13
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/init_user.sql:/docker-entrypoint-initdb.d/init_user.sql

  postgres-order:
    image: postgres:13
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db # Change to your desired order DB name
    ports:
      - "5433:5432" # Different port to avoid conflict with user DB
    volumes:
      - ./init-scripts/init_order.sql:/docker-entrypoint-initdb.d/init_order.sql # Optional init script

  postgres-inventory:
    image: postgres:13
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
      POSTGRES_DB: inventory_db
    ports:
      - "5434:5432"
    volumes:
      - ./init-scripts/init_inventory.sql:/docker-entrypoint-initdb.d/init_inventory.sql
